[package]
name = "termkit"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
tokio = { version = "1.38.0", features = ["rt", "net", "sync"] }

[dev-dependencies]
tokio = { version = "1.38.0", features = ["rt", "net", "sync", "macros", "rt-multi-thread"] }
